apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: anomaly-detector
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      completions: 1
      parallelism: 1
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: anomaly-detector
            image: opeco17/anomaly-detector:latest
            imagePullPolicy: IfNotPresent
            command: ["python3",  "main.py"]
            env:
            - name: TARGET_WEB_PAGE_URI
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: TARGET_WEB_PAGE_URI
            - name: PLATFORM
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: PLATFORM
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: ELASTICSEARCH_URL
            - name: INDEX_PREFIX
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: INDEX_PREFIX
            - name: INDEX_TEMPLATE_NAME
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: INDEX_TEMPLATE_NAME
            - name: SEARCH_QUERY_FILE
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: SEARCH_QUERY_FILE
            - name: ALERT_TARGET_METRICS
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: ALERT_TARGET_METRICS
            - name: METRICS_SEQUENCE_LENGTH
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: METRICS_SEQUENCE_LENGTH
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: LOG_LEVEL
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: WEBHOOK_URL       
            - name: TZ
              valueFrom:
                configMapKeyRef:
                    name: general-config
                    key: TZ
          restartPolicy: Never