apiVersion: v1
kind: ConfigMap
metadata:
  name: general-config
data:
  TARGET_WEB_PAGE_URI: https://www.google.com/
  PLATFORM: desktop
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_URL: http://elasticsearch:9200
  INDEX_PREFIX: pagespeed-metrics
  INDEX_TEMPLATE_NAME: pagespeed-metrics-index-template
  INDEX_TEMPLATE_FILE: index_template.json
  SEARCH_QUERY_FILE: search_query.json
  ALERT_TARGET_METRICS: server_response_time
  METRICS_SEQUENCE_LENGTH: "30"
  ALLOWABLE_NUMBER_OF_FAILURES: "3"
  THRESHOLD_RATE: "0.3"
  LOG_LEVEL: INFO
  WEBHOOK_URL: https://hooks.slack.com/services/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
  TZ: Asia/Tokyo